Update shortcode-give.html.twig
CuBoulder/ucb_migration_shortcodes pull request #52
Opened 2024-06-18 22:42 UTC by jnicholCU

Changed html template to match the ckeditor 5 button plugin html. 

Button does not have a light gray or dark gray option so I set dark to be black and light to be gray as to emulate the same color options. 

I also added logic for style to be set to "default" instead of "regular" as there was no differentiation in D7

Resolves #34

2024-06-21 15:23 UTC, timurtripp commented
I don't think we want this wrapped in a `<p>`, unless I'm mistaken?

2024-06-21 15:27 UTC, timurtripp requested changes
See above

2024-06-21 21:11 UTC, timurtripp requested changes
Needs sanity check on size and style; remove unnecessary newlines and whitespace.

2024-06-21 21:17 UTC, timurtripp commented
Use `raw` instead of `t`

2024-06-25 15:13 UTC, jnicholCU commented
Closing because of some weirdness with the git branch. 
Reopening from new branch.

2024-06-25 15:13 UTC, closed without merging